version: "3.7"
services:

  unpackerr:
    image: "golift/unpackerr"
    container_name: "unpackerr"
    volumes:
      - /mnt/HostDownloads:/downloads
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # General config
      - UN_DEBUG=false  #Turns on more logs
      - UN_LOG_FILE=None  #Optionally provide a file path to write logs
      - UN_LOG_FILES=10  #Log files to keep after rotating. 0 disables rotation
      - UN_LOG_FILE_MB=10  #Max size of log files in megabytes
      - UN_INTERVAL=2m  #How often apps are polled, recommend 1m to 5m
      - UN_START_DELAY=1m  #Files are queued at least this long before extraction
      - UN_RETRY_DELAY=5m  #Failed extractions are retried after at least this long
      - UN_MAX_RETRIES=3  #Times to retry failed extractions. 0 = unlimited
      - UN_PARALLEL=1  #Concurrent extractions, only recommend 1
      - UN_FILE_MODE=0644  #Extracted files are written with this mode
      - UN_DIR_MODE=0755  #Extracted folders are written with this mode
      # Sonarr Config
      - UN_SONARR_0_URL=  #Something like: http://localhost:8989, http://sonarr:8989
      - UN_SONARR_0_API_KEY=  #No Default. Provide URL and API key if you use Sonarr
      - UN_SONARR_0_PATHS_0=/downloads  # List of paths where content is downloaded for Sonarr
      - UN_SONARR_0_PROTOCOLS=torrent  #Protocols to process. Alt: torrent,usenet
      - UN_SONARR_0_TIMEOUT=10s  #How long to wait for the app to respond
      - UN_SONARR_0_DELETE_ORIG=false  #Delete archives after import? Recommend not setting this to true
      - UN_SONARR_0_DELETE_DELAY=5m  #Extracts are deleted this long after import, -1 to disable
      # Radarr Config
      - UN_RADARR_0_URL=  #Something like: http://localhost:7878, http://radarr:8989
      - UN_RADARR_0_API_KEY=  #No Default. Provide URL and API key if you use radarr
      - UN_RADARR_0_PATHS_0=/downloads  # List of paths where content is downloaded for radarr
      - UN_RADARR_0_PROTOCOLS=torrent  #Protocols to process. Alt: torrent,usenet
      - UN_RADARR_0_TIMEOUT=10s  #How long to wait for the app to respond
      - UN_RADARR_0_DELETE_ORIG=false  #Delete archives after import? Recommend not setting this to true
      - UN_RADARR_0_DELETE_DELAY=5m  #Extracts are deleted this long after import, -1 to disable
      # Lidarr Config
      - UN_LIDARR_0_URL=  #Something like: http://localhost:8686, http://lidarr:8989
      - UN_LIDARR_0_API_KEY=  #No Default. Provide URL and API key if you use Lidarr
      - UN_LIDARR_0_PATHS_0=/downloads  # List of paths where content is downloaded for Lidarr
      - UN_LIDARR_0_PROTOCOLS=torrent  #Protocols to process. Alt: torrent,usenet
      - UN_LIDARR_0_TIMEOUT=10s  #How long to wait for the app to respond
      - UN_LIDARR_0_DELETE_ORIG=false  #Delete archives after import? Recommend not setting this to true
      - UN_LIDARR_0_DELETE_DELAY=5m  #Extracts are deleted this long after import, -1 to disable
      # Readarr Config
      - UN_READARR_0_URL=  #Something like: http://localhost:8787, http://readarr:8989
      - UN_READARR_0_API_KEY=  #No Default. Provide URL and API key if you use Readarr
      - UN_READARR_0_PATHS_0=/downloads  # List of paths where content is downloaded for Readarr
      - UN_READARR_0_PROTOCOLS=torrent  #Protocols to process. Alt: torrent,usenet
      - UN_READARR_0_TIMEOUT=10s  #How long to wait for the app to respond
      - UN_READARR_0_DELETE_ORIG=false  #Delete archives after import? Recommend not setting this to true
      - UN_READARR_0_DELETE_DELAY=5m  #Extracts are deleted this long after import, -1 to disable
      # Folder Config
      - UN_FOLDER_0_PATH=  #No Default; folder to watch for archives. Not for Starr apps
      - UN_FOLDER_0_EXTRACT_PATH=  #Where to extract to. Default is the same as path
      - UN_FOLDER_0_DELETE_AFTER=10m  #Delete extracted files and/or archives after this duration; 0 disables
      - UN_FOLDER_0_DELETE_ORIGINAL=false  #Delete archives after successful extraction
      - UN_FOLDER_0_DELETE_FILES=false  #Delete extracted files after successful extraction
      - UN_FOLDER_0_MOVE_BACK=false  #Move extracted items back into original folder
      # Webhook Config
      - UN_WEBHOOK_0_URL=  #No Default; URL to send POST webhook to
      - UN_WEBHOOK_0_NAME=  #Defaults to URL; provide an optional name to hide the URL in logs
      - UN_WEBHOOK_0_NICKNAME=Unpackerr  #Passed into templates for telegram, discord and slack hooks
      - UN_WEBHOOK_0_CHANNEL=""  #Passed into templates for slack.com webhooks
      - UN_WEBHOOK_0_TIMEOUT=  #Defaults to global timeout, usually 10s
      - UN_WEBHOOK_0_SILENT=false  #Hide successful POSTs from logs
      - UN_WEBHOOK_0_IGNORE_SSL=false  #Ignore invalid SSL certificates
      - UN_WEBHOOK_0_EXCLUDE=[]  #List of apps to exclude: radarr, sonarr, folders, etc
      - UN_WEBHOOK_0_EVENTS=[0]  #List of event IDs to send (shown below)
      - UN_WEBHOOK_0_TEMPLATE_PATH=""  #Instead of an internal template, provide your own
      - UN_WEBHOOK_0_CONTENT_TYPE=application/json  #Content-Type header sent to webhook
      #Event IDs (not all of these are used in webhooks): 0 = all, 1 = queued, 2 = extracting, 3 = extract failed, 4 = extracted, 5 = imported, 6 = deleting, 7 = delete failed, 8 = deleted
      #Webhook Notes
      #Nickname should equal the chat_id value in Telegram webhooks.
      #Channel is used as destination channel for Slack. It's not used in others.
      #Nickname and Channel may be used as custom values in custom templates.
      #Name is only used in logs, but it's also available as a template value as {{name}}.
    security_opt:
      - no-new-privileges:true
