package unpackerr

import (
	"fmt"
	"path/filepath"
	"regexp"
	"strings"

	"golift.io/starr/lidarr"
)

// numberedTrackPattern matches filenames generated by CUE splitting: "NN - Title.flac".
var numberedTrackPattern = regexp.MustCompile(`^\d{2,3} - .+\.flac$`)

// LidarrConfig represents the input data for a Lidarr server.
type LidarrConfig struct {
	StarrConfig
	SplitFlac      bool          `json:"split_flac" toml:"split_flac" xml:"split_flac" yaml:"split_flac"`
	Queue          *lidarr.Queue `json:"-"          toml:"-"          xml:"-"          yaml:"-"`
	*lidarr.Lidarr `json:"-"          toml:"-"          xml:"-"          yaml:"-"`
}

func (l *LidarrConfig) pollQueue() (int, int, error) {
	if l.Lidarr == nil {
		l.connect()
	}

	queue, err := l.GetQueue(DefaultQueuePageSize, 1)
	if err != nil {
		return 0, 0, fmt.Errorf("getting queue: %w", err)
	}

	l.Queue = queue

	return queue.TotalRecords, len(queue.Records), nil
}

func (l *LidarrConfig) queueViews() []queueView {
	if l.Queue == nil {
		return nil
	}

	out := make([]queueView, 0, len(l.Queue.Records))

	for _, rec := range l.Queue.Records {
		out = append(out, queueView{
			Title:      rec.Title,
			Status:     rec.Status,
			Protocol:   rec.Protocol,
			OutputPath: rec.OutputPath,
			Size:       rec.Size,
			Sizeleft:   rec.Sizeleft,
			IDs: map[string]any{
				"title":      rec.Title,
				"artistId":   rec.ArtistID,
				"albumId":    rec.AlbumID,
				"downloadId": rec.DownloadID,
				"reason":     buildStatusReason(rec.Status, rec.StatusMessages),
			},
		})
	}

	return out
}

func (l *LidarrConfig) hasQueueTitle(name string) bool {
	if l.Queue == nil {
		return false
	}

	for _, rec := range l.Queue.Records {
		if rec.Title == name {
			return true
		}
	}

	return false
}

func (l *LidarrConfig) tweakExtract(item *Extract, rec queueView) {
	item.SplitFlac = l.SplitFlac
	item.OutputPath = rec.OutputPath
}

func (l *LidarrConfig) logExtra() string {
	return fmt.Sprintf(", split_flac:%v", l.SplitFlac)
}

// lidarrServerByURL returns the Lidarr server config that matches the given URL, or nil.
func (u *Unpackerr) lidarrServerByURL(url string) *LidarrConfig {
	for _, server := range u.Lidarr {
		if server.URL == url {
			return server
		}
	}

	return nil
}

// crossPlatformBase returns the filename from a path that may use either forward slashes
// or backslashes as separators. On Linux, filepath.Base does not split on backslashes,
// so Windows/UNC paths from Starr apps would return the entire path instead of the filename.
func crossPlatformBase(path string) string {
	return filepath.Base(filepath.FromSlash(strings.ReplaceAll(path, `\`, `/`)))
}

// filterManualImportToSplitTracks returns only outputs whose filename matches a split track file.
// This excludes the original audio file we split from, which Lidarr would otherwise try and fail
// to import. Comparison uses basenames (filenames only) so it works across platforms — the extraction
// host (e.g. Linux) may use different paths than the Starr app (e.g. Windows).
func filterManualImportToSplitTracks(outputs []*lidarr.ManualImportOutput, item *Extract) []*lidarr.ManualImportOutput {
	if item == nil || item.Resp == nil || len(item.Resp.NewFiles) == 0 {
		return nil // Signal that we couldn't filter; caller should try fallback.
	}

	splitFiles := make(map[string]struct{}, len(item.Resp.NewFiles))
	for _, p := range item.Resp.NewFiles {
		splitFiles[strings.ToLower(crossPlatformBase(p))] = struct{}{}
	}

	filtered := outputs[:0] // reusable memory

	for _, out := range outputs {
		if out != nil && out.Path != "" {
			if _, ok := splitFiles[strings.ToLower(crossPlatformBase(out.Path))]; ok {
				filtered = append(filtered, out)
			}
		}
	}

	return filtered
}

// filterManualImportToNumberedTracks returns outputs whose filename matches the CUE-split
// naming pattern (NN - Title.flac). This is a fallback when NewFiles tracking is unavailable
// (e.g. after MoveFiles moves tracks back to the original folder).
func filterManualImportToNumberedTracks(outputs []*lidarr.ManualImportOutput) []*lidarr.ManualImportOutput {
	filtered := make([]*lidarr.ManualImportOutput, 0, len(outputs))

	for _, out := range outputs {
		if out != nil && out.Path != "" {
			base := crossPlatformBase(out.Path)
			if numberedTrackPattern.MatchString(base) {
				filtered = append(filtered, out)
			}
		}
	}

	return filtered
}

// filterSplitOutputs filters ManualImport outputs to only include split track files.
// First tries matching against NewFiles (basename comparison), then falls back to the
// CUE-split naming pattern (NN - Title.flac) when NewFiles is unavailable.
func (u *Unpackerr) filterSplitOutputs(
	outputs []*lidarr.ManualImportOutput, item *Extract,
) []*lidarr.ManualImportOutput {
	allOutputs := make([]*lidarr.ManualImportOutput, len(outputs))
	copy(allOutputs, outputs)

	filtered := filterManualImportToSplitTracks(allOutputs, item)
	if len(filtered) > 0 {
		return filtered
	}

	u.Printf("[Lidarr] No split track files matched via NewFiles for %s; trying numbered track pattern", item.Path)

	return filterManualImportToNumberedTracks(allOutputs)
}

// importSplitFlacTracks runs in a goroutine after a Lidarr FLAC+CUE split extraction completes.
// It asks Lidarr for the manual import list for the extract folder and sends the ManualImport command
// so Lidarr imports the split track files.
func (u *Unpackerr) importSplitFlacTracks(item *Extract, server *LidarrConfig) {
	if server == nil {
		u.Printf("[Lidarr] No Lidarr server found for manual import, this might be a bug: %s", item.Path)
		return
	}

	downloadID, _ := item.IDs["downloadId"].(string)
	artistID, _ := item.IDs["artistId"].(int64)

	// Use OutputPath (the Starr app's view of the path) for ManualImport when available.
	// The extraction host may use a different mount/path than the Starr app (e.g., Linux vs Windows UNC).
	importFolder := item.Path
	if item.OutputPath != "" {
		importFolder = item.OutputPath
	}

	outputs, err := server.ManualImport(&lidarr.ManualImportParams{
		Folder:               importFolder,
		DownloadID:           downloadID,
		ArtistID:             artistID,
		FilterExistingFiles:  false,
		ReplaceExistingFiles: true,
	})
	if err != nil {
		u.Errorf("[Lidarr] Manual import list failed for %s: %v", item.Path, err)
		return
	}

	if len(outputs) == 0 {
		u.Printf("[Lidarr] No files returned for manual import (folder: %s); import manually in Lidarr", item.Path)
		return
	}

	outputs = u.filterSplitOutputs(outputs, item)
	if len(outputs) == 0 {
		u.Printf("[Lidarr] No split track files to import (folder: %s)", item.Path)
		return
	}

	cmd := lidarr.ManualImportCommandFromOutputs(outputs, true)
	if cmd == nil {
		u.Printf("[Lidarr] No importable files for manual import: %s", item.Path)
		return
	}

	u.Debugf("[Lidarr] Sending manual import command: replaceExisting=%v, importMode=%q, files=%d",
		cmd.ReplaceExistingFiles, cmd.ImportMode, len(cmd.Files))

	if _, err = server.SendManualImportCommand(cmd); err != nil {
		u.Errorf("[Lidarr] Manual import command failed for %s: %v", item.Path, err)
		return
	}

	u.Printf("[Lidarr] Manual import triggered for %d files: %s", len(cmd.Files), item.Path)
}
