#!/bin/bash

# This upgrades the docker client on the Docker Cloud server to a version
# that contains the `docker manifest` command, so we can build with QEMU.

docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
